version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "20m"

services:

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    #ports:
    #  - '127.0.0.1:1025:1025'
    logging: *default-logging

  db:
    image: mariadb
    restart: unless-stopped
    env_file:
      - mysql.env
    volumes:
      # - ./docker/mariadb/config:/etc/mysql/conf.d:ro
      - ./db/data:/var/lib/mysql
    ports:
      - '3307:3306'
    logging: *default-logging

  nginx:
    build: ./docker/nginx/build
    image: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/config:/etc/nginx/conf.d:ro
      - ./projects:/srv/project/
      - ./docker/nginx/acme-challenge:/usr/share/nginx/html:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      # -"443:443"
      - "8025:8025"
      - "8080:8080"
      - "8000:8000"
    logging: *default-logging

  adminer:
    image: adminer
    restart: unless-stopped

  php-82:
    build: ./docker/php-82/build
    image: php-82
    restart: unless-stopped
    env_file:
      - mysql.env
    volumes:
      - ./docker/php-82/config/msmtprc:/etc/msmtprc:ro
      - ./docker/php-82/config/php.ini:/usr/local/etc/php/conf.d/my.ini:ro
      - ./docker/php-82/config/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php-82/composer/:/root/.composer/
      - ./projects/:/srv/project/
    logging: *default-logging

  php-8:
    build: ./docker/php-8/build
    image: php-8
    restart: unless-stopped
    working_dir: /srv/project/
    env_file:
      - mysql.env
    volumes:
      - ./docker/php-8/config/msmtprc:/etc/msmtprc:ro
      - ./docker/php-8/config/php.ini:/usr/local/etc/php/conf.d/my.ini:ro
      - ./docker/php-8/config/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php-8/composer/:/root/.composer/
      - ./projects/:/srv/project/
    logging: *default-logging
  #sqldata:
  #  image: mcr.microsoft.com/mssql/server:2017-latest
  #  environment:
  #    - SA_PASSWORD=SWMsecret!
  #    - ACCEPT_EULA=Y
  #  ports:
  #    - "5434:1433"
